In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('regional_to_muni.csv.gz')

df

,geocodigo,uf,id_regional,regional,macroregional_id,macroregional
0,1100189,Rondônia,11002,Cafe,1101,II – CACOAL
1,1100296,Rondônia,11005,Zona Da Mata,1101,II – CACOAL
2,1101476,Rondônia,11002,Cafe,1101,II – CACOAL
3,1301902,Amazonas,13004,Medio Amazonas,1303,LESTE
4,1302702,Amazonas,13003,Rio Madeira,1303,LESTE
...,...,...,...,...,...,...
5565,5222302,Goiás,52018,Sao Patricio Ii,5209,CENTRO-OESTE
5566,5222005,Goiás,52002,Centro Sul,5210,CENTRO SUDESTE
5567,5222054,Goiás,52002,Centro Sul,5210,CENTRO SUDESTE
5568,5221908,Goiás,52002,Centro Sul,5210,CENTRO SUDESTE
5569,5300108,Distrito Federal,53001,Distrito Federal,5302,DISTRITO FEDERAL

In [3]:
df.loc[df.geocodigo == 3549805.]

,geocodigo,uf,id_regional,regional,macroregional_id,macroregional
4281,3549805,São Paulo,35155,Sao Jose Do Rio Preto,3531,RRAS12